//Authentication Types
export const AUTHENTICATION_REQUEST = "AUTHENTICATION_REQUEST";
export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS";
export const AUTHENTICATION_FAILURE = "AUTHENTICATION_FAILURE";

// Status

export const USER_LOGGED_IN = "LOGGED_IN";
export const USER_LOGGED_OUT = "LOGGED_OUT";
